In [18]:
import numpy as np

In [19]:
#create a 0 dimension array
a = np.array([])

In [20]:
#create a 1 dimension array
b = np.array([1,2,4,5])

In [21]:
#create a 2 dimension array
c = np.array([[5,6],[9,8]])

In [22]:
# Get Dimension
a.ndim

1

In [23]:
b.ndim

1

In [24]:
c.ndim

2

In [25]:
# Get Shape
a.shape

(0,)

In [26]:
b.shape

(4,)

In [27]:
c.shape

(2, 2)

In [28]:
# Get Type
#a.dtype
a.dtype

dtype('float64')

In [29]:
b.dtype

dtype('int32')

In [30]:
c.dtype

dtype('int32')

In [31]:
# Get Size
#a.itemsize
a.itemsize

8

In [32]:
b.itemsize

4

In [33]:
c.itemsize

4

In [34]:
# Get total size
#a.nbytes
a.nbytes

0

In [35]:
b.nbytes

16

In [36]:
c.nbytes

16

In [37]:
# Get number of elements
#a.size
a.size

0

In [38]:
# Get number of elements
#a.size
b.size

4

In [39]:
# Get number of elements
#a.size
c.size

4

In [40]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [41]:
#Create an array with variable name a and the following contents (shape (3, 4)):
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
#What is the array shape?
a.shape

(3, 4)

In [43]:
#What is the array ndim?
a.ndim

2

In [44]:
#How about the len of the array?
a.size

12

In [45]:
#Create a 1D array from 2 through 5 inclusive.
a = np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [46]:
#Make an array with 10 equally spaced elements between 2 and 5 inclusive.
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [47]:
#Make an all-ones array shape (4, 4).
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
#Make an identity array shape (6, 6).
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [49]:
#Make this array with a single Python / numpy command:
# 1  0  0
# 0  2  0
# 0  0  3
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [50]:
#Make a Array of random numbers shape 3, 5
np.random.rand(3,5)

array([[1.91710254e-01, 5.10907299e-01, 1.88153509e-04, 3.58656273e-01,
        7.78990092e-01],
       [5.99247841e-01, 6.47305634e-01, 2.29639399e-01, 3.56121602e-01,
        3.45741076e-02],
       [2.14818708e-02, 7.09544524e-01, 3.38140258e-01, 8.58586230e-01,
        4.72043167e-01]])

In [51]:
#Create the following array, call this a:
# 2  7 12  0
# 3  9  3  4
# 4  0  1  3
a = np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
print(a)

[[ 2  7 12  0]
 [ 3  9  3  4]
 [ 4  0  1  3]]


In [52]:
#Get the 2nd row of a
a[2,:]

array([4, 0, 1, 3])

In [53]:
#Get the 3rd column of a
a[:,3]

array([0, 4, 3])

In [54]:
#Create the following arrays (with correct data types):

# [[1, 1, 1, 1],
#  [1, 1, 1, 1],
#  [1, 1, 1, 2],
#  [1, 6, 1, 1]]

a = np.ones((4,4))
a[2,3]=2
a[3,1]=6
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 2.]
 [1. 6. 1. 1.]]


In [55]:
# [[0., 0., 0., 0., 0.],
#  [2., 0., 0., 0., 0.],
#  [0., 3., 0., 0., 0.],
#  [0., 0., 4., 0., 0.],
#  [0., 0., 0., 5., 0.],
#  [0., 0., 0., 0., 6.]]

a = np.zeros((6,5))
a[1,0]=2
a[2,1]=3
a[3,2]=4
a[4,3]=5
a[5,4]=6
print(a)

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 6.]]
