In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
b = np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
c = np.array([1.0,2.1,4.3])
c

array([1. , 2.1, 4.3])

# Size of the Array

In [15]:
a.size

3

In [16]:
b.size

6

In [18]:
c.size

3

# Dimensions

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [19]:
c.ndim

1

# Shape

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [20]:
c.shape

(3,)

# DataType

In [21]:
a.dtype

dtype('int32')

In [22]:
b.dtype

dtype('int32')

In [23]:
c.dtype

dtype('float64')

# Itemsize

In [24]:
a.itemsize

4

In [25]:
b.itemsize

4

In [26]:
c.itemsize

8

# Accessing/Changing specific elements, rows, columns

In [3]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [11]:
#get a specific element in an array [r,c]
a[0,3]

4

In [5]:
a[1,-1]

12

In [12]:
#get an entire row
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [13]:
#get an entire column
a[:,4]

array([ 5, 11])

In [10]:
#start Index, end Index, step size
a[0,1:4:2]

array([2, 4])

In [9]:
a[1,2:6:3]

array([ 9, 12])

In [14]:
#3D array
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
d[1,0,0]

5

In [16]:
d[:,1,:]=[[5,8],[3,1]]
print(d)

[[[1 2]
  [5 8]]

 [[5 6]
  [3 1]]]


# Create arrays using numPy functions

In [18]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((1,2))

array([[1., 1.]])

In [20]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [22]:
# Random number
np.random.rand(2,3)

array([[0.04314226, 0.22622815, 0.75668818],
       [0.22721759, 0.33559065, 0.7027293 ]])

In [27]:
np.random.randint(1,14,size=(3,4))

array([[ 4, 13, 13, 11],
       [ 6, 12,  2,  7],
       [ 1,  2, 12,  8]])

In [28]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Mathematics on numPy Arrays

In [29]:
f = np.array([1,2,4,5])
print(f)

[1 2 4 5]


In [30]:
f+2

array([3, 4, 6, 7])

In [31]:
f-3

array([-2, -1,  1,  2])

In [32]:
f*5

array([ 5, 10, 20, 25])

In [33]:
f/3

array([0.33333333, 0.66666667, 1.33333333, 1.66666667])

In [35]:
g = np.array([5,4,8,9])
print(g)

[5 4 8 9]


In [36]:
f+g # should be same size
f+g

array([ 6,  6, 12, 14])

In [34]:
e = np.array(["Naseela",21,True])
print(e)

['Naseela' '21' 'True']


In [37]:
f**2

array([ 1,  4, 16, 25], dtype=int32)

In [38]:
np.cos(f)

array([ 0.54030231, -0.41614684, -0.65364362,  0.28366219])

In [39]:
np.log(f)

array([0.        , 0.69314718, 1.38629436, 1.60943791])

# Statistics on Numpy array

In [40]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [41]:
np.min(a)

1

In [42]:
np.max(a)

6

In [43]:
np.sum(a)

21

In [44]:
# Using Text File
datafile = np.genfromtxt('data.txt', delimiter = ',')

In [45]:
datafile

array([[ 1.,  5.,  6.,  7.,  3.,  4., 55., 67., 87.],
       [ 4., 23., 14., 67.,  3.,  4.,  8., 34.,  6.],
       [ 7.,  5., 90., 44.,  5., 15., 36.,  5.,  8.]])

In [46]:
datafile*2

array([[  2.,  10.,  12.,  14.,   6.,   8., 110., 134., 174.],
       [  8.,  46.,  28., 134.,   6.,   8.,  16.,  68.,  12.],
       [ 14.,  10., 180.,  88.,  10.,  30.,  72.,  10.,  16.]])

In [47]:
datafileint = datafile.astype('int32')

In [48]:
datafile

array([[ 1.,  5.,  6.,  7.,  3.,  4., 55., 67., 87.],
       [ 4., 23., 14., 67.,  3.,  4.,  8., 34.,  6.],
       [ 7.,  5., 90., 44.,  5., 15., 36.,  5.,  8.]])

In [49]:
(datafile>50)

array([[False, False, False, False, False, False,  True,  True,  True],
       [False, False, False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False]])